version: '3.8'
services:
    device-controller:
        image: device-controller:latest
        init: true
        build:
            context: .
            dockerfile: Containerfile
        environment:
            - NODE_ENV=production
            - CONFIG_FILE_PATH=/data/config.json
        volumes:
            - ./config.json:/data/config.json:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
